---
- name: retrieve network configurations
  hosts: all
  gather_facts: no
  tasks:
    - name: backup configuration
      dellemc.os6.os6_config:
        backup: true
        backup_options:
          dir_path: /tmp/
          filename: "{{ inventory_hostname }}.txt"
      register: config_output
      when: ansible_network_os is defined
    - name: create time stamp for play
      set_fact:
        datetime: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M') }}"
      delegate_to: backup-server
      delegate_facts: true
      run_once: true
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /export/local/ansible/backup/
        state: directory
      delegate_to: backup-server
      become: true
      run_once: true
    - name: save configuration to backup server
      copy:
        src: "{{ config_output.backup_path }}"
        dest: "/export/local/ansible/backup/{{hostvars['backup-server'].datetime}}/"
      when: config_output is defined
      become: true
      delegate_to: backup-server
