---
- name: call middleware
  hosts: localhost
  gather_facts: no
  tasks:
    - debug:
        msg: "API call to {{ nodes }}"
        #verbosity: 1
    - name: Create the API body
      set_fact:
        api_body: "{{ api_body | default([]) | union([{'host': item}]) }}"
      loop: "{{ nodes }}"
    - name: Update the API body
      set_fact:
        api_body: "{{ {'hosts' : api_body} }}"
    - debug:
        msg: "{{ api_body }}"
        #verbosity: 1
    - name: Make the API call
      uri:
        url: http://45.21.227.192:8181/service/host/reboot/
        method: POST
        body_format: json
        body: "{{ api_body }}"
      register: return_data
    - debug:
        msg: "{{ return_data }}"
