---
- name: Simple playbook
  hosts: node1,node2
  gather_facts: no
  vars:
    isam_up: yes
  tasks:
    - name: Ensure that python3 is installed
      yum:
        name: python3
        state: present
      become: yes
      tags: python3
    # - name: Start the python3 webserver
    #   command: "python3 -m http.server 8080 "
    #   when: isam_up
    #   tags: python3
    - name: Check reverse proxy
      debug:
        msg: "Status OK"
      tags: reverse_proxy
    - name: Check WebSeal
      debug:
        msg: "WebSeal OK"
      tags: webseal
    - name: Check MGA
      uri:
        url: "http://{{ inventory_hostname }}:8080"
        status_code: 200
      tags: mga
      register: response
      failed_when: false

    - debug:
        msg: "{{ response }}"
        verbosity: 1
      tags: mga

    - name: No issues
      debug:
        msg: "No errors found on {{ inventory_hostname }}"
      when: "'OK' in response.msg"
      tags:
        - systems_up
        - mga

    - name: Nodes with failures
      set_stats:
        data:
          nodes: "{{ inventory_hostname | list }}"
      when: "'OK' not in response.msg"
      tags: mga
    - fail:
        msg: some systems failed
      when: "'OK' not in response.msg"
      tags: mga
