---
version: 3
dependencies:
  galaxy: requirements.yml
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8:2.15.4-4
options:
  package_manager_path: /usr/bin/microdnf
